### ISSUE TITLE
Fix for Band_Vega _zpFluxesFlam Astropy units mismatch

### ISSUE THREAD

**Issue by emirkmo** [chrisfrohmaier/what_the_flux#1]
Hi Chris (& Maria),

I noticed that running the example notebook from https://github.com/maria-vincenzi/PyCoCo_templates/blob/master/Codes/0_toFlux.ipynb gives an error with the current version of what_the_flux.

the arrays being fed into np.interp in _zpFluxesFlam() function, under the Band_Vega class, are a mismatch of astropy.units.quantity.Quantity and regular numpy floats. This is coming from the fact that w_Vega and f_Vega are np.float32 arrays but the wavelength_array returned from self.filterFLambdaBins() returns an astropy.units.quantity.Quantity array of angstroms. 

I fixed this by modifying line 284 from

`_Vega_interp = np.interp(wavelength_array, w_Vega, f_Vega)*u.erg/u.s/u.cm**2/u.AA`

to

`_Vega_interp = np.interp(wavelength_array.value, w_Vega, f_Vega)*u.erg/u.s/u.cm**2/u.AA`

As far as I can tell, everywhere else, the units are matched correctly (either no units for all arrays or all arrays as astropy Quantity objects).

Let me know if you would be ok with me submitting this change as a pull request. I think a similar fix is needed for PyCoCo_templates bundled version of what_the_flux as well. 

I tested this error and fix with astropy version 4.0.

Best regards,

Emir

P.S.: Very helpful library! I replaced my own script with it and hence the errors. I also think installation instructions might be useful to add to the readme.

Emir Karamehmetoglu
emir.k@phys.au.dk
Postdoctoral researcher
Department of Physics and Astronomy, Aarhus University

**Comment by chrisfrohmaier** [comment]
Hi Emir,

Glad to hear someone is using what_the_flux! I noticed the units mismatch too when I was running some code locally. I fixed it in the same way as you but didn't push my changes to github.
Feel free to submit a pull request and I'll check it and merge.

Cheers,
Chris

**Comment by emirkmo** [comment]
I realized I never got around to making the pull request, but it looks like your commit in April fixed it here and elsewhere.
