### ISSUE TITLE
Install/build instructions

### ISSUE THREAD

**Issue by emirkmo** [chrisfrohmaier/what_the_flux#2]
I don't think this needs to be a package (although that would of course make it easier). But I chose to install this using Conda with:

conda-develop /path/to/what_the_flux-master

Which obviously makes what_the_flux.py available for import in your current environment.

When doing this, I also had to change the Vega fits file import to point to the right path, so line 36 to:

`Vega = fits.open('/path/to/what_the_flux-master/alpha_lyr_stis_006.fits')`

In case this is helpful to others trying to run what_the_flux. Perhaps you can add this info to the README or provide better installation instructions (very possible I'm doing something pathological).

**Comment by chrisfrohmaier** [comment]
Thanks for the suggestion. I agree I need to improve all aspects of the documentation!
I'll add this to my to-do list.

(I always thought it was just me and Maria using what_the_flux, since we work in the same building I never felt pressure to write instructions. This will change!)

**Comment by emirkmo** [comment]
Looks like this has been fixed as well!
